// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDRGnBfXTGrm3e9w4VjzyYqDKmGQZrUm74',
    appId: '1:363534831662:web:75e63292c41a3eea50cfbf',
    messagingSenderId: '363534831662',
    projectId: 'easyrider-c3a50',
    authDomain: 'easyrider-c3a50.firebaseapp.com',
    storageBucket: 'easyrider-c3a50.appspot.com',
    measurementId: 'G-Q1E0EG82T7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDlj4COxyvyHr0jjcIH3NMWQkswUej1b8g',
    appId: '1:363534831662:android:d1b2c496bb8af31950cfbf',
    messagingSenderId: '363534831662',
    projectId: 'easyrider-c3a50',
    storageBucket: 'easyrider-c3a50.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCDouqAak-WP3hVt9i2lhsK8aoR8lEgvhU',
    appId: '1:363534831662:ios:60c157937ec7bf6c50cfbf',
    messagingSenderId: '363534831662',
    projectId: 'easyrider-c3a50',
    storageBucket: 'easyrider-c3a50.appspot.com',
    iosBundleId: 'com.easyrider.rider',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCDouqAak-WP3hVt9i2lhsK8aoR8lEgvhU',
    appId: '1:363534831662:ios:81aa3c54ce3f545250cfbf',
    messagingSenderId: '363534831662',
    projectId: 'easyrider-c3a50',
    storageBucket: 'easyrider-c3a50.appspot.com',
    iosBundleId: 'com.easyrider.rider.RunnerTests',
  );
}
